### ISSUE TITLE
使用了!=比较基本类型的包装类

### ISSUE THREAD

**Issue by 360CodeSafe** [sanluan/PublicCMS#14]
你好,我在查看PublicCMS代码时发现一个问题:
在文件
[/publiccmscore/src/main/java/com/publiccms/controller/admin/cms/CmsCategoryAdminController.java](https://github.com/sanluan/PublicCMS/blob/786eed685b1fd6e7ccca2929b913c9f438606a11/publiccms-parent/publiccms-core/src/main/java/com/publiccms/controller/admin/cms/CmsCategoryAdminController.java#L103)103行
代码`                if (null != oldEntity.getParentId() && oldEntity.getParentId() != entity.getParentId()) {`

使用了!=比较基本类型的包装类;
!=运算符当两个操作数(oldEntity.getParentId(),entity.getParentId())都是包装器类型时，判定标准为他们是否指向同一个对象;而没有比较两个操作数的值。

同时由于Integer在[-128,127]值之间有缓存,所以使用!=比较Integer在Integer的值都在[-128,127]之间会返回正确结果,其他情况下都会有问题。

**Comment by sanluan** [comment]
感觉您细心发现的问题
