### ISSUE TITLE
v4.0 新增的站点后台登陆不了

### ISSUE THREAD

**Issue by 333zjb** [sanluan/PublicCMS#23]
服务器centos7 tomcat8 jdk1.8.0_201.
后台新增了一个站点，对应的nginx配置也按照推荐配置好了，访问第二个站点的前台地址和后台地址也都能访问，只是访问后台时输入用户名和密码后没有反应，也没报任何错误。

**Comment by sanluan** [comment]
可以在浏览器开发人员工具看网络请求记录
或者加交流群找我帮你远程解决

**Comment by 333zjb** [comment]
站点的nginx配置里面这一段 rewrite /publiccms/(.*)$ /$1 permanent; 我把permanent删除掉后就能正常登陆了，感谢您的解答。
