### ISSUE TITLE
页面片段管理手动添加推荐位内容遍历不出数据

### ISSUE THREAD

**Issue by gaoxiaobo0513** [sanluan/PublicCMS#24]
v2017版本中，页面>页面片段管理>添加推荐位数据
手动输入推荐位数据时（非选择已发布文章）无法遍历出数据

**Comment by sanluan** [comment]
页面片段重新发布了么

**Comment by sanluan** [comment]
后台模版与前台模版用的是相同的逻辑展示数据的问题如果后台能看到数据 前台就可以遍历出来

**Comment by gaoxiaobo0513** [comment]
后台可以看到数据列表，前台无法展示；奇怪的是如果我选择已发布的文章前台是可以正常展示的/(ㄒoㄒ)/~~
