### ISSUE TITLE
Forging x-forwarded-for data

### ISSUE THREAD

**Issue by blackjliuyun** [sanluan/PublicCMS#26]
Hello,I found a bug that the administrator account login ip is at risk of being forged while logging in
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/23147261/69009584-96046600-0991-11ea-955d-ce64898218cc.png">

the question is  as follows：
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/23147261/69009651-715cbe00-0992-11ea-8122-b883263c50cb.png">

<img width="827" alt="image" src="https://user-images.githubusercontent.com/23147261/69009669-ac5ef180-0992-11ea-81b7-a827680a15e1.png">

**Comment by sanluan** [comment]
增加了多个ip记录功能,防止用户欺骗,也防止用户java容器没有增加真实ip获取时 拿到的全是反向代理ip的问题
