### ISSUE TITLE
Background storage XSS

### ISSUE THREAD

**Issue by wind226** [sanluan/PublicCMS#27]
Background storage XSS
step1：
https://cms.publiccms.com/case.html Submit case
![image](https://user-images.githubusercontent.com/24953996/69142990-eea74080-0b02-11ea-8909-6139218755ba.png)
step2：
Administrator review submit case trigger xss
![image](https://user-images.githubusercontent.com/24953996/69143072-26ae8380-0b03-11ea-8dc6-8ff39e4e5d63.png)
Click to trigger xss
![image](https://user-images.githubusercontent.com/24953996/69143110-38902680-0b03-11ea-837a-e552dbeb83d7.png)

**Comment by sanluan** [comment]
抱歉 这个问题暂时没办法避免 文章正文必须是富文本的
下个版本将会把投稿内容和普通内容区分开 审核前 取消投稿的预览

**Comment by wind226** [comment]
> 抱歉，这个问题暂时没办法避免文章正文必须是富文本的
> 下个版本将会把投稿内容和普通内容区分开审核前取消投稿的预览

你可以过滤敏感字符，或者转义双引号，单引号，尖括号就能避免xss

**Comment by sanluan** [comment]
刚才提交了代码 目前的解决方法是标识投稿文章，对于未审核的投稿文章 默认做安全转义

**Comment by wind226** [comment]
> 先前提交了代码目前的解决方法是标识投稿文章，对于未审核的投稿文章默认做安全转义
做安全转义这个办法是可以

**Comment by sanluan** [comment]
非常感谢发现的这个bug
