### ISSUE TITLE
Should we remove unnecessary 'public' in interface?

### ISSUE THREAD

**Issue by dengliming** [sanluan/PublicCMS#44]
我看了下源码现在很多接口类里面的变量和方法都声明了public，可以去掉，@sanluan 你觉得怎样？

**Comment by sanluan** [comment]
嗯 应该去掉 还有接口中字段的 public static final修饰符也该去掉 部分基类的方法也可以放到接口中

**Comment by dengliming** [comment]
@sanluan 👍  我晚点提个PR
