### ISSUE TITLE
There is an XSS vulnerability in managing background file management

### ISSUE THREAD

**Issue by lixuyong2014** [sanluan/PublicCMS#64]
Storage XSS
On this page as shown in the figure,
![image](https://user-images.githubusercontent.com/83060696/161267969-9c09a683-820e-4aea-a89e-4e2553745f72.png)
click 创建文件
![image](https://user-images.githubusercontent.com/83060696/161268198-82b48d78-c69f-4786-849a-74f8635c875e.png)
As shown in the figure below, creat xx.html file， enter <script>alert(1)</script>，click 保存
![image](https://user-images.githubusercontent.com/83060696/161268579-c9ea065a-5e04-47cf-8cdd-96bf81361675.png)

Then click 查看

![image](https://user-images.githubusercontent.com/83060696/161268601-3153e876-9711-4598-821c-b61eaa58b6fb.png)

Trigger vulnerability

![image](https://user-images.githubusercontent.com/83060696/161268630-373af43a-d54b-43e1-a5c1-cd54e7660295.png)

**Comment by sanluan** [comment]
这是一个在线编辑html的基础功能 不是安全漏洞 任何干扰编辑html的措施都将使功能失效
