### ISSUE TITLE
后台存储型xss

### ISSUE THREAD

**Issue by kevinoclam** [sanluan/PublicCMS#66]
也是在文件管理，不过跟之前那位提的不一样，这个是文件名处的解析，不是文件内容（我试了下，文件内容的已经不能触发了，看了下已经转义了）
![image](https://user-images.githubusercontent.com/13563369/190042028-b65145fe-35a7-49b6-ab26-9847f777c4d2.png)
直接创建文件或者上传也行，文件名中带有xss的payload，如上图所示
![image](https://user-images.githubusercontent.com/13563369/190042128-ca201b73-788a-404e-a143-acaf2a43d560.png)
点击修改，打开的新标签可以触发
![image](https://user-images.githubusercontent.com/13563369/190042191-a0192d06-163b-4140-8f48-35cf8e8903c6.png)
![image](https://user-images.githubusercontent.com/13563369/190042208-596a50bc-dfb1-482c-883e-50911b851efa.png)
可以看到触发位置是在标签栏里的文件名展示处

版本：
![image](https://user-images.githubusercontent.com/13563369/190043335-0741456c-ec17-4854-9572-3b2b0583cec9.png)

纯后台的话，危害不大，，我没在默认模板找到提供前台操作这个web文件管理系统的，不清楚原有设计是否包含这种情况，如果前台能操作到的话，还是有较高风险的

**Comment by JDragonZ** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sanluan** [comment]
新版本已经修改
