### ISSUE TITLE
A vulnerability exists in PublicCMS V4.0.202204.d and below, Cross-site request forgery(CSRF)

### ISSUE THREAD

**Issue by h18192h** [sanluan/PublicCMS#68]
PublicCMS V4.0.202204.d has a vulnerability known as Cross-Site Request Forgery (CSRF). Located in the background--> maintenance--> user management--> increase users. The vulnerability could lead to the addition of administrator account management owner content or the addition of department head account management department owner content
![image](https://user-images.githubusercontent.com/83074322/207323111-3445de38-a05c-4b69-8375-77d9601d71d1.png)
1.Enter the background--> maintenance--> user management--> increase users
![image](https://user-images.githubusercontent.com/83074322/207324918-7c2fcb63-58af-486a-9f57-887f068b29f9.png)
2.Simulates the request to increase the number of users and constructs a payload
![image](https://user-images.githubusercontent.com/83074322/207325032-fd2d0327-f344-46fe-8327-6e6b48f9e9ec.png)
The figure above shows the constructed payload, adding an administrator through CSRF implementation, the account is "TestUser", the password is "test", and the user name is "CSRFTEST"
3.The browser opens the file
![image](https://user-images.githubusercontent.com/83074322/207327617-a8997682-0004-4696-98f4-953039037bd1.png)
Refresh the background user management page:
![image](https://user-images.githubusercontent.com/83074322/207327648-8f8f96ea-1b4d-4acf-9ee2-463c15c923f7.png)
Test whether the newly added administrator can log in
![image](https://user-images.githubusercontent.com/83074322/207327925-ace6b7c7-5337-4838-8ddc-82e847df59ec.png)
![image](https://user-images.githubusercontent.com/83074322/207328140-17c7540f-320c-495c-a14f-aa36ae5db963.png)
Login successful！

**Comment by sanluan** [comment]
You just copied a copy of the form for you by the system. You can't build the form of other users, and other users can't build this form as your identity.
