### ISSUE TITLE
A vulnerability exists in PublicCMS  V4.0.202302.c and below, Arbitrary file write

### ISSUE THREAD

**Issue by LiangChen-Ye** [sanluan/PublicCMS#72]
在最新版本下
![图片](https://user-images.githubusercontent.com/74550480/231361768-65267533-d110-4e19-8f30-fa64b2945778.png)
漏洞触发点：/admin/sysSite/doUploadSitefile

![图片](https://user-images.githubusercontent.com/74550480/231362332-a4a1c530-ddd9-447f-8e02-bf529b9819e6.png)

针对上传文件名originalName没有做过滤，可以通过../../实现路径穿越，从而在任意位置写入文件（但文件名必须满足后缀-site.zip）

![图片](https://user-images.githubusercontent.com/74550480/231362350-12c0b3be-be83-41d7-94f5-cac6b1850058.png)

测试：发送如下报文

![图片](https://user-images.githubusercontent.com/74550480/231362402-f97d56c6-ea40-426e-9f31-e8c7c4f9a330.png)

成功使文件写入到E:/目录下

测试单位：山东大学网络空间安全学院

**Comment by JDragonZ** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sanluan** [comment]
问题确实存在 近期降修复 感谢渗透测试
