### ISSUE TITLE
Unable to load static files

### ISSUE THREAD

**Issue by SnowyThinker** [sanluan/PublicCMS#73]
![image](https://github.com/sanluan/PublicCMS/assets/4386778/e9138bb2-f03b-4d3c-84e0-6df4619abfba)

--------------------------------------------------------------------------------------------------------
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)
--------------------------------------------------------------------------------------------------------
Window 10 x64

**Comment by JDragonZ** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sanluan** [comment]
Find the Edit Configurations menu item in the Run menu
![image](https://github.com/sanluan/PublicCMS/assets/12441887/7841099d-687d-4dde-93f2-9019f2347ce7)

**Comment by SnowyThinker** [comment]
It works, thanks
