### ISSUE TITLE
初始化只能通过localhost访问吗

### ISSUE THREAD

**Issue by yanyi5496** [sanluan/PublicCMS#75]
在ubuntu上通过docker启动了publiccms，无法通过IP访问到publiccms的初始化界面。
是否默认只支持localhost方式，或者需要某些配置才可。

**Comment by JDragonZ** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sanluan** [comment]
不要做这种没有任何依据 不符合任何事实得猜测
ip不能访问说明你输入得ip或端口不对
