### ISSUE TITLE
There is an SSRF vulnerability in publiccms V4.0.202302.e, whice allow attackers to access the website of intranet or detect whether the port is open

### ISSUE THREAD

**Issue by aoaoaoe** [sanluan/PublicCMS#77]
1.After logging into the backend system，add an application authorization to obtain an appKey and appSecret
![图片](https://github.com/sanluan/PublicCMS/assets/48166761/b0f6e0eb-7a4c-43ea-bd7e-6647bb60e708)

2.Obtain apptoken through the /api/appToken interface with appkey and appsecret
![图片](https://github.com/sanluan/PublicCMS/assets/48166761/dd4c802d-5eb5-4d29-b6c0-eb5675dc9294)

3.The SSRF vulnerability exists in the "parameters" parameter of the /api/method/getHtml interface, which can be used to access the website of intranet,for example,access 127.0.0.1:8080/admin and return the page content.
![图片](https://github.com/sanluan/PublicCMS/assets/48166761/6e52ecc7-de17-4f8c-a12e-8b3fed4ee8ac)

4.In addition, it can also be used to detect open ports on the intranet system.
When the port is open, the response time is only a few milliseconds, but when the port is not open, the response time is about 2000 milliseconds.This obvious response time difference can be used to determine whether the port is open.
![图片](https://github.com/sanluan/PublicCMS/assets/48166761/401154e8-7ae1-4d7d-8ae8-9a9d14849523)
![图片](https://github.com/sanluan/PublicCMS/assets/48166761/19596c3e-c9ce-48c2-bc38-072f8bf4df2c)

5.The vulnerability entrance is in `MethodController.java`. It receives an "appToken" and "parameters" parameter, assigns the "parameters" parameters to the list, and then calls `method.execute(request, list)`, the "method" is the method specified by {name}
![图片](https://github.com/sanluan/PublicCMS/assets/48166761/b3b5a8b0-e598-49da-ae99-c65ee288e2fb)

6.When {name} is "getHtml", enter the` execute(@SuppressWarnings("unused") HttpServletRequest request, List<TemplateModel> arguments) `method of `BaseMethod.java`
![图片](https://github.com/sanluan/PublicCMS/assets/48166761/62f2785e-6838-4380-a421-f651776caac9)

7.Then enter the `execute(List<TemplateModel> arguments)` method of `GetHtmlMethod.java`, take the values from the incoming parameters and assign them to the "url" and "body", and then determine whether the "body" is empty. If not, send a post request to the "url". If it is empty, send a get request to the "url".
![图片](https://github.com/sanluan/PublicCMS/assets/48166761/971f36fd-7a97-41f1-b329-464f99b14c25)

8.After sending the request, the returned content is directly returned to the client. During this period, no detection is made on whether the "paramaters" parameter is illegal, and there is no detection of ssrf-related interceptors, so ssrf can be directly performed and obtained through the server request. Any URL address can be used to access some sensitive resources on the intranet or detect the port of the intranet system.
![图片](https://github.com/sanluan/PublicCMS/assets/48166761/83f83604-fd9f-4688-8d2b-30cb8f7dbf79)
![图片](https://github.com/sanluan/PublicCMS/assets/48166761/672fa02c-787e-431d-81d6-d7e068039b1c)

**Comment by sanluan** [comment]
This is a permission-controlled feature and we don't consider it a bug
