### ISSUE TITLE
There is a SSRF vulnerability in the lastest version of PublicCMS- V4.0.202302.e

### ISSUE THREAD

**Issue by haoami** [sanluan/PublicCMS#78]
Hello,I found a SSRF vulnerability in the lastest version of PublicCMS- V4.0.202302.e

The vulnerability lies in the fact that there is no protection when using ueditor to obtain image resources, so that HTTP can be used to request any URL for ssrf.
![](http://39.107.239.30:3000/uploads/50d06ad5-b17c-49d8-8939-ec98041b1c2f.png)
So just get the request directly
![](http://39.107.239.30:3000/uploads/c8ff0a1d-2210-481c-a7cd-c74c1cec74e3.png)
When detecting the internal network port, if the port does not exist, a rejection will be returned.
![](http://39.107.239.30:3000/uploads/88c5171d-2eb6-474d-beb9-dd323e0d022d.png)
If it exists, return error
![](http://39.107.239.30:3000/uploads/579839df-73a9-4344-b4b6-99bffda5ebc0.png)

**Comment by flushhhhh** [comment]
不是吧大哥，前面那个漏洞已经够水了，你还学他搞个更水的- -

**Comment by haoami** [comment]
哈哈哈哈，不好意思啊，之前就看到这个洞了感觉挺水就没提issue，看别人发了个我也发了😂😂



发自我的iPhone


------------------ Original ------------------
From: flushhhhh ***@***.***&gt;
Date: Sat,Nov 18,2023 11:39 PM
To: sanluan/PublicCMS ***@***.***&gt;
Cc: KKfine ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [sanluan/PublicCMS] There is a SSRF vulnerability in the lastestversion of PublicCMS- V4.0.202302.e (Issue #78)





 
不是吧大哥，前面那个漏洞已经够水了，你还学他搞个更水的- -

**Comment by unafraid-fearless** [comment]
> Hello,I found a SSRF vulnerability in the lastest version of PublicCMS- V4.0.202302.e
> 
> The vulnerability lies in the fact that there is no protection when using ueditor to obtain image resources, so that HTTP can be used to request any URL for ssrf. ![](https://camo.githubusercontent.com/7a695e2512362b78dfa6c747b27f2da73c3e8092558e73799a1acf33835f9d51/687474703a2f2f33392e3130372e3233392e33303a333030302f75706c6f6164732f35306430366164352d623137632d343964382d383933392d6563393830343162316332662e706e67) So just get the request directly ![](https://camo.githubusercontent.com/1f40274910337a0fe8df66ad409452a307f091c5a503111f498fbeae1c768220/687474703a2f2f33392e3130372e3233392e33303a333030302f75706c6f6164732f63386666306131642d323231302d343831632d613763642d6337346331636563373465332e706e67) When detecting the internal network port, if the port does not exist, a rejection will be returned. ![](https://camo.githubusercontent.com/e00cb66630538f9698e88917f6153716ad54034b16870bf0f75beb8ff56aa889/687474703a2f2f33392e3130372e3233392e33303a333030302f75706c6f6164732f38386335313731642d326562362d343734642d626562392d6464333233653064303232642e706e67) If it exists, return error ![](https://camo.githubusercontent.com/67ad37f7496e956f3c6505ce2798a83f8c0e460d51919b35c943bce7c5e1c66f/687474703a2f2f33392e3130372e3233392e33303a333030302f75706c6f6164732f35373938333964662d373361392d343334342d623462362d3939626666646135656263302e706e67)

hahaha

**Comment by JDragonZ** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by RetrO-hash** [comment]
> Hello,I found a SSRF vulnerability in the lastest version of PublicCMS- V4.0.202302.e
> 
> The vulnerability lies in the fact that there is no protection when using ueditor to obtain image resources, so that HTTP can be used to request any URL for ssrf. ![](https://camo.githubusercontent.com/5119b1a60ae45ccfeb55f3205cb8adadfb89a5d1a53d0791c6b9a3972c5ee1ba/687474703a2f2f33392e3130372e3233392e33303a333030302f75706c6f6164732f35306430366164352d623137632d343964382d383933392d6563393830343162316332662e706e67) So just get the request directly ![](https://camo.githubusercontent.com/f25033269a6164c08c32b657a2d677b78396b2ebac000f4b4b67adfbae5b6b8f/687474703a2f2f33392e3130372e3233392e33303a333030302f75706c6f6164732f63386666306131642d323231302d343831632d613763642d6337346331636563373465332e706e67) When detecting the internal network port, if the port does not exist, a rejection will be returned. ![](https://camo.githubusercontent.com/bc60686ce176200d011ca95d80768a53dcdb4628e093a4654dfdbac49bc7a018/687474703a2f2f33392e3130372e3233392e33303a333030302f75706c6f6164732f38386335313731642d326562362d343734642d626562392d6464333233653064303232642e706e67) If it exists, return error ![](https://camo.githubusercontent.com/aea955d14e65a3c79ed04ccf12ee63fc3d7c5c79fd2a011534165e3676d7c4c4/687474703a2f2f33392e3130372e3233392e33303a333030302f75706c6f6164732f35373938333964662d373361392d343334342d623462362d3939626666646135656263302e706e67)

sb

**Comment by haoami** [comment]
> > Hello,I found a SSRF vulnerability in the lastest version of PublicCMS- V4.0.202302.e
> > The vulnerability lies in the fact that there is no protection when using ueditor to obtain image resources, so that HTTP can be used to request any URL for ssrf. ![](https://camo.githubusercontent.com/5119b1a60ae45ccfeb55f3205cb8adadfb89a5d1a53d0791c6b9a3972c5ee1ba/687474703a2f2f33392e3130372e3233392e33303a333030302f75706c6f6164732f35306430366164352d623137632d343964382d383933392d6563393830343162316332662e706e67) So just get the request directly ![](https://camo.githubusercontent.com/f25033269a6164c08c32b657a2d677b78396b2ebac000f4b4b67adfbae5b6b8f/687474703a2f2f33392e3130372e3233392e33303a333030302f75706c6f6164732f63386666306131642d323231302d343831632d613763642d6337346331636563373465332e706e67) When detecting the internal network port, if the port does not exist, a rejection will be returned. ![](https://camo.githubusercontent.com/bc60686ce176200d011ca95d80768a53dcdb4628e093a4654dfdbac49bc7a018/687474703a2f2f33392e3130372e3233392e33303a333030302f75706c6f6164732f38386335313731642d326562362d343734642d626562392d6464333233653064303232642e706e67) If it exists, return error ![](https://camo.githubusercontent.com/aea955d14e65a3c79ed04ccf12ee63fc3d7c5c79fd2a011534165e3676d7c4c4/687474703a2f2f33392e3130372e3233392e33303a333030302f75706c6f6164732f35373938333964662d373361392d343334342d623462362d3939626666646135656263302e706e67)
> 
> sb

Poor quality
